spring:
  application:
    name: config-default
  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
